### PR TITLE
Add dashboard link and icons to profile menu

### PR DESCRIPTION
**Pull request by vidvidvid**
## Overview

**What features/fixes does this PR include?**

The link to dashboard was missing so I added it to the profile popover along with some icons.
The metagame icon in the top left corner now leads to `/dashboard` if the person browsing the page is logged in and to `/` -> `/players` if the person is not logged in. The latter case will change to the landing page once it's built.

## Follow up Improvement Ideas

- [ ] better icons @davort ?
- [ ] perhaps we could instead move the dashboard link to the megamenu next to the community and the rest and make it visible only to the player.

## Assets

Screenshot 2021-12-20 at 19 00 08

### CODE REVIEW

**Comment by davort** [comment]
Hey, @vidvidvid, this is cool, great that you added the link there. Can you say whether the MetaGame logo, on the far left in the header, is also linked to the Dashboard, because it should be?

**Comment by davort** [comment]
That would be awesome @vidvidvid 
It was supposedly solved in https://github.com/MetaFam/TheGame/issues/851 but apparently not? Dunno what happened, but we need that logo linked 😊

**Comment by vidvidvid** [comment]
close & open for redeploy

**Comment by vidvidvid** [comment]
Ah well technically clicking the metagame icon leads to 'home', which is set to redirect to 'players' atm. Will change it to dashboard!

**Review by alalonde — APPROVED** [review]

**Pull request merged**
