### PR TITLE
Add announcements from Discord to a guild's page

### LINKED ISSUE #894: On guild page, pull in announcements from Discord channel
### What would you like to be added?

We currently have an empty "announcements" section on a guild's page:
image

For guilds that have a [connected discord server](https://my.metagame.wtf/join/guild), we could pull in the "announcements" discord channel automatically. 

This should probably happen on-demand using a Hasura remote action, like how a guild's discord roles are currently fetched.

Outstanding questions:
- Is there a standardized way of identifying public "events" or "announcements" channels via the discord API?
  - If not, we would need the guild owner (as specified in our DB) to provide the channel ID
- Any additional permissions required?

### Why is this needed?

The data is already there and we should have access to it, why not?

### PR DESCRIPTION
**Pull request by alalonde**
## Overview

**What features/fixes does this PR include?**
A new remote schema relationship `discordAnnouncements` has been added to the `guild` table. This fetches the last 10 messages from all of the guild's discord server's "news" channels. We also use the `showdown` library to convert the message markdown to HTML.

Closes #894

This also changes the default permissions for Discord when launching the guild onboarding process, addressing #1240 .

## TODO

- [x] I think this needs a bit of love from @davort and our designers.. Seems we should be capping the height of the announcements section, and perhaps adding a "view all" much like the players section which would display all the content in a modal. We could also only fetch the first e.g. 100 characters from each "announcement" to save space.
- [x] We should make this configurable by each guild, by adding a `show_discord_announcements` flag to the `guild_metadata` table as well as the edit guild form. Whether it is opt-in or not by default is up for debate.
- [ ] It would be useful to show a "authorize announcement fetching" to guild admins on their own guild page. This would just flow them through the Discord auth process, allowing them to authorize the additional permissions.  Already-joined guilds would need to go through this process for the announcement fetching to work.

## Assets

image

### CODE REVIEW

**Comment by peth-yursick** [comment]
> Thoughts @peth-yursick ?

Idk how I'm only now seeing it but it made my day!
Agree it needs a bit of @davort's UI love.
Is there any reason why limited to only last 10 announcements if its going to be hidden under "view all"?
I think it should be opt-in by default, personally don't see why any guild would not find it beneficial that their announcements are published inside MetaGame if they're public announcements. 🤷‍♂️

**Comment by davort** [comment]
The preview link doesn't seem to be working for me. Where could I take a look at the current design?

**Comment by alalonde** [comment]
@davort It's back :) 

https://frontend-pr-1244-mjhnbmqqna-uk.a.run.app/guild/metafam

**Comment by alalonde** [comment]
This needs a bit more testing but is close. See PR description for details

**Comment by peth-yursick** [comment]
> https://frontend-pr-1244-mjhnbmqqna-uk.a.run.app/guild/metafam

Was there a new test deployment after this?
For this I'm still getting:
image

**Comment by alalonde** [comment]
Hmm, perhaps you checked too soon? https://frontend-pr-1244-mjhnbmqqna-uk.a.run.app/guild/metafam

**Comment by alalonde** [comment]
One technical note: The `show_discord_announcements` flag basically serves as a cache for a guild's given discord permissions `Read Messages` and `Read Message History`. If a guild re-triggers the oauth flow (e.g. from the /join/guild page), they can change those permissions.

**Review by dysbulic — DISMISSED** [review]
I think everything looks workaable.

**Pull request merged**
