### PR TITLE
added seed-graph as a new remote schema

### PR DESCRIPTION
**Pull request by dan13ram**
Adding this to make it easier to query (sort, filter, etc) the seed-graph directly via a single graphql url from frontend

### CODE REVIEW

**Review by pakokrew — COMMENTED** [review]
Don't know if we should do this. Why do you need it ?

Problem when adding remote-schema, is that external schema are merged onto our root schema. Here, it will add `transfers + userTokens` to our Root schema, next to our `Users, Guilds,...` etc
I understood that it's on Hasura's roadmap to add namespaces or more custom import of remote schemas, but not yet available, and we'd really need that.

But adding the remote schema really depends on why we do this. 
Will the subgraph directly called by the frontend ?
If it will be only called from a custom backend handler (that'll return a list of patron for instance) we don't need it to our public schema and keep it clean.

**Comment by dan13ram** [comment]
> Don't know if we should do this. Why do you need it ?

Hey you can see how I'm using it in https://github.com/MetaFam/TheGame/pull/395
This way we are only doing a total of 2 calls to our backend.

But I agree to your point of keeping our schema clean. I'll see if we can do this directly in a backend handler and return only a list of patrons.

**Comment by dan13ram** [comment]
@pakokrew I've updated the logic and no longer using a new remote-schema

**Review by pakokrew — APPROVED** [review]
Nice like this :)

**Pull request merged**
