### PR TITLE
add query to the wiki url to hide the header

### PR DESCRIPTION
**Pull request by luxumbra**
- wiki issue [355](https://github.com/MetaFam/metagame-wiki/issues/355)
- this improves display of the wiki when it is embedded in MetaOS.

## Overview

**What features/fixes does this PR include?**
adds a query to the url for the wiki so it hides and applies some specific styles to the wiki header when it is embedded in metaOS. 
We've also removed the old wiki homepage and added a 301 redirect in Vercel to handle the removal of `/docs/` from wiki URLs.

**Please provide the GitHub issue number**
[Wiki issue 355](https://github.com/MetaFam/metagame-wiki/issues/355)

*Requires https://github.com/MetaFam/metagame-wiki/pull/356 to be merged first.*

## Follow up Improvement Ideas

- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Review by alalonde — COMMENTED** [review]
A quick search of the codebase reveals a whole bunch of links to wiki.metagame.wtf, do we want to change those too?

**Comment by luxumbra** [comment]
> A quick search of the codebase reveals a whole bunch of links to wiki.metagame.wtf, do we want to change those too?

Any links that currently link out to the wiki will work as normal but yes, there's a couple that should be updated - 2 in the megamenu for a start. I'll update them.

**Comment by luxumbra** [comment]
@alalonde i have updated the 3 other wiki references in the megamenu but i think other links to the wiki that are present throughout only link out to the wiki and don't iframe the wiki in MetaOS. 

Would be nice if we didn't have to link out and could keep all wiki links iframed but that is a bigger job that we could maybe tackle after v1.0?

**Comment by luxumbra** [comment]
@alalonde I am currently doing #1356 which i thought i could tag onto this PR. As far as the other work in this PR goes, I've addressed the issue with the other megamenu items getting missed in the initial work.

**Review by dysbulic — APPROVED** [review]
I've no problems.

**Pull request merged**
