### PR TITLE
Show DAO memberships across Ethereum, Polygon, and xDai mainnets

### PR DESCRIPTION
**Pull request by mattcan**
This Pull Request pulls DAOs from the DaoHaus subgraphs on TheGraph for Ethereum, Polygon, and xDai mainnets.

with-chain-and-contract

Some details about the change:

* when there is no title for a DAO, a formatted contract ID is shown
* when there is no known logo, a logo for the chain that the DAO is on is shown

Related: #549

### CODE REVIEW

**Comment by mattcan** [comment]
Not sure why the deployment is failing, unfortunately I can't see the error. Let me know if there is something I can fix, please.

**Comment by alalonde** [comment]
```

@metafam/web: Error occurred prerendering page "/players". Read more: https://nextjs.org/docs/messages/prerender-error
--
23:00:22.455 | @metafam/web: Error: Error serializing `.urqlState["3475206522"].error.graphQLErrors[0].path` returned from `getStaticProps` in "/players".
23:00:22.455 | @metafam/web: Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
23:00:22.455 | @metafam/web:     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:95)
23:00:22.456 | @metafam/web:     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:490
23:00:22.456 | @metafam/web:     at Array.every (&lt;anonymous&gt;)
23:00:22.456 | @metafam/web:     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:291)
23:00:22.456 | @metafam/web:     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:769
23:00:22.457 | @metafam/web:     at Array.every (&lt;anonymous&gt;)
23:00:22.457 | @metafam/web:     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:706)
23:00:22.458 | @metafam/web:     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:490
23:00:22.458 | @metafam/web:     at Array.every (&lt;anonymous&gt;)
23:00:22.458 | @metafam/web:     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:7:291)
```

**Comment by mattcan** [comment]
@alalonde do you have any other tips? I have been trying to recreate the error but no success so far. I'm guessing it may be a problem with my local as the only way I can get a list of players is by making this patch:

```diff
diff --git a/packages/web/graphql/getPlayers.ts b/packages/web/graphql/getPlayers.ts
index 20c9b5e..cd3f872 100644
--- a/packages/web/graphql/getPlayers.ts
+++ b/packages/web/graphql/getPlayers.ts
@@ -28,9 +28,6 @@ gql`
       offset: $offset
       limit: $limit
       where: {
-        Player_Skills: { Skill: { category: { _eq: $skillCategory } } }
-        playerType: { id: { _eq: $playerType } }
-        availability_hours: { _gte: $availability }
         timezone: { _eq: $timezone }
         _or: [
           { username: { _ilike: $search } }
```

I have tried:

* running all of the backend with `yarn docker:start`
* running only hasura and the database with `docker-compose up --build database hasura` and `yarn backend:dev`
* building with `yarn web:build` and `yarn backend:build`

**Comment by dan13ram** [comment]
@mattcan I understood the issue. This PR has changes on the backend as well as the frontend. 
Please break them into two different PRs. 
First PR would be *only* for the backend and the second *only* for the frontend changes.

**Comment by mattcan** [comment]
> @mattcan Sorry for the delay in response.
> May I suggest running `yarn web:build` with the backend as production db?
> 
> ```
> NEXT_PUBLIC_GRAPHQL_URL=https://api.metagame.wtf/v1/graphql
> ```
> 
> I just ran this locally and got the same errors as on vercel.

Ah that did it, thanks! I missed that in the guide.

**Comment by mattcan** [comment]
> @mattcan The issue with deployment is probably because it has changes on the backend as well as the frontend.
> Please break them into two different PRs.
> First PR would be _only_ for the backend and the second _only_ for the frontend changes.
> 
> Also please do a rebase with `develop`.

Can you explain why that might be? I am a bit concerned about splitting the change because the backend change will pull in a bunch of data that the frontend isn't really equipped to deal with. The site will probably work but will look really bad if only one PR is merged.

**Comment by dan13ram** [comment]
> Can you explain why that might be? I am a bit concerned about splitting the change because the backend change will pull in a bunch of data that the frontend isn't really equipped to deal with. The site will probably work but will look really bad if only one PR is merged.

Hey @mattcan, this is because our backend is hosted on render while the frontend is hosted on vercel. So we will need to split it up so that there is no downtime. Hope that makes sense.

**Comment by mattcan** [comment]
> > Can you explain why that might be? I am a bit concerned about splitting the change because the backend change will pull in a bunch of data that the frontend isn't really equipped to deal with. The site will probably work but will look really bad if only one PR is merged.
> 
> Hey @mattcan, this is because our backend is hosted on render while the frontend is hosted on vercel. So we will need to split it up so that there is no downtime. Hope that makes sense.

Thanks for clearing that up @dan13ram. I'll get this split up today :+1:

**Comment by dan13ram** [comment]
Cheers @mattcan. Regarding things not looking good, we could maybe merge the modal changes first which would work irrespective of the backend changes. 

But that makes it 3 different PRs, so I think two should be fine here.

Also we are first merging to `develop` and then `master`. So we should be safe to push all the changes in one PR to `master` I think even if `vercel` deploy fails there. @alalonde any thoughts ?

**Comment by alalonde** [comment]
> @mattcan The issue with deployment is probably because it has changes on the backend as well as the frontend.
> Please break them into two different PRs.
> First PR would be _only_ for the backend and the second _only_ for the frontend changes.

Depending on the changes required, this isn't always possible, as the original backend change may break the frontend. With the improvements to our CI, this shouldn't be necessary anymore. The only thing that won't work is Vercel's PR deployment which I think we can live with.

**Comment by mattcan** [comment]
> > @mattcan The issue with deployment is probably because it has changes on the backend as well as the frontend.
> > Please break them into two different PRs.
> > First PR would be _only_ for the backend and the second _only_ for the frontend changes.
> 
> Depending on the changes required, this isn't always possible, as the original backend change may break the frontend. With the improvements to our CI, this shouldn't be necessary anymore. The only thing that won't work is Vercel's PR deployment which I think we can live with.

So my understanding is that I probably don't need to split the PR and the branch build only really only deploys the frontend. To avoid headaches, I've split the backend changes out to #643. I think it doesn't look great but the site won't be broken, which is good news. I'll close this PR and the frontend changes from the develop branch once #643 is merged.

**Pull request closed without merging**
