### PR TITLE
Seeds page updates #1413

### LINKED ISSUE #1413: Updating the Seeds page
It was built a while ago, there's a bunch of it out of date by now..

Things to change:
- [x] Add the new illustration & maybe put it below the intro paragraph instead of side-by-side?
- [x] These two blocks should be completely removed. First one because the Seed Fund time has passed & the second one because there is no easy way for keeping the FAQ up to date, add more questions etc; + makes it symmetrical after removing Seed Fund.
   - image
- [x] "Become a Patron" block text should be updated.
   - Instead of everything written on there right now, it should say this:
      - Though some use cases exist, they're not meaningfully contributing to the treasury yet & the rest are just ideas. Main reasons you'd want to become a patron right now:
      - Because you love the idea of MetaGame & want to see it succeed.
      - You want to become a part of MetaGame but don't have time to actively contribute.
      - Interested? Go [through here](https://metagame.wtf/join/patron).
- [x] "Get Ranked" block text should also be updated
   - Instead of current text, it should say this:
      - As you might know already both players & patrons have leaderboards & ranked leagues as well as perks (which will all be finalized at the end of _Phase I_, ~June 2023:
      - 🥉 Bronze Founder or Funder
      - 🥈 Silver Founder or Funder
      - 🥇 Golden Founder or Funder
      - 🔘 Platinum Founder or Funder
      - 💎 Diamond Founder or Funder
      - You may check the full list of [patron perks](https://metagame.wtf/join/patron) here & know the one for players will be similar. All feedback welcome.
- [x] Blocks themselves as well as the pop-ups should be transparent blur like the rest of the blocks & popups on the platform
- [x] Lastly, idk why it says SEED everywhere all caps instead of Seed. Would be good to replace everywhere, including page tab

### PR DESCRIPTION
**Pull request by HHH-GH**
## Overview

**What features/fixes does this PR include?**
This covers text and layout updates requested by @peth-yursick 

**Please provide the GitHub issue number**

Closes #1413

## Follow up Improvement Ideas

- [x] Needs a better Seed icon at the top
- [x] The Buying & Selling Seeds popup still mentions Seed fund - not sure if we want to keep that in there.

## Implementation

Nothin' special

**Side effects**

## Assets

I added the new `seed-diagram.png` flowchart into `assets` as it's shared by a couple of pages now.

### CODE REVIEW

**Comment by HHH-GH** [comment]
>     * [ ]  Needs a better Seed icon at the top

Definitely needs a better Seed icon. The SVG looks a mess in Firefox. (It's okay in Chrome though)

**Ideas**
- Seed emoji
- $$ emoji
- Something else

https://frontend-pr-1426-mjhnbmqqna-uk.a.run.app/seeds


**Screenshots**  
**Chrome**
image

**Firefox :/**  
image

**Comment by peth-yursick** [comment]
> * Needs a better Seed icon at the top
Here u go ser:
seed logo

> * The Buying & Selling Seeds popup still mentions Seed fund - not sure if we want to keep that in there.

Great catch! Definitely not.

Also noticed the popup windows are still as in original..
image

**Comment by HHH-GH** [comment]
Seeds icon, Seeds flowchart, and popup background all updated.

The mention of Seed fund was deleted and replaced with "or we can do it for you, just ask. " (Similar to what's on the Patron join page in the [*Buy & forget about it* section at the bottom of the page](https://metagame.wtf/join/patron))

See the screenshot below for popup background and "we can do it for you, just ask"

image

**Comment by peth-yursick** [comment]
> The mention of Seed fund was deleted and replaced with "or we can do it for you, just ask. " (Similar to what's on the Patron join page in the [_Buy & forget about it_ section at the bottom of the page](https://metagame.wtf/join/patron))

Thank you! Would be good to also add a link to the patrons page if you haven't.

I also noticed these weird white lines on the logo..
image
It doesnt seem to be a problem on the image itself.
But its pretty minor & might not be noticeable on other screens, idk, if you dont know how to fix it, feel free to just ignore & merge.

Other than that, looks great! Thank you 🙏

**Comment by HHH-GH** [comment]
I've 
- Fixed the issue with the Seed image (something weird the with transparency)
- Added another link to Patron's Join page on the Planting & Watering Seeds page
- Tidied up some of the links

AND
- found that the 'ask on Discord' link in the Buying & Selling Seeds popup is either expired or invalid (https://discord.com/invite/8THHVwfd)

@peth-yursick  Should it link to the the MetaGame Discord, or a specific channel? lmk, I'll fix it up and push these latest updates, and with that we should be done with this.

**Comment by dysbulic** [comment]
@peth-yursick, you shouldn't have alpha composite issues like you're seeing with a SVG.

@HHH-GH, the funky sizing of the SEED SVG you started with could be my fault. I have a tendency to remove the `height` and `width` attributes from SVGs and just rely on the `viewBox` for sizing. Theoretically this should be transparent, but maybe it had an unexpected effect.

If you pad the SVG does it shrink it in Chrome? Can you use padding to get them the same size?

**Comment by HHH-GH** [comment]
I ended up replacing the SVG Seed icon with the PNG that peth posted in the comments above. 

That file had the transparency issues seen in the screenshot.

I edited the image to add a tiny drop shadow around the edges of the artwork, and that fixed it. 

If there's an SVG file of that icon I can definitely try it.

About the SVGs,  

I'm having some *slight* difficulties with them. 

For e.g., the Seeds diagram/flowchart  
- I wanted to compare the filesize of the SVG vs. a PNG (the full SVG is 1.18MB, which feels pretty heavy for a webpage)
- When I open it in Illustrator, there's only the layer with white text, but not the tree in the middle and all the images.

Is the SVG coming out of Figma? I'll try and export a PNG from there. (I did this for the [Guild sign up page](https://metagame.wtf/join/guild), and the PNG version of that flowchart is about 130 KB vs. about 1 MB for the SVG version, and the PNG version would obviously load a lot more quickly.

**Comment by HHH-GH** [comment]
I've pushed the latest version:
- the Seeds icon at the top, with the transparency fixed
- 'ask on Discord' link in the Buying & Selling Seeds popup is pointed to the MetaGame server, but not a specific channel in the server

**Comment by dysbulic** [comment]
I finally got ahold of the SVG that Figma is generating. It is probably, literally, 1000⨯ larger than it needs to be.

SVG supports text elements and CSS fonts just like HTML. So, less than probably ⅒KiB for all the text in the image. All the text in the Figma image though are paths made up of tens of thousands of points taking up hundreds of KiB.

The central part isn't a SVG at all really. Figma rasterized everything to a PNG and it is inserted into the file base64 encoded.

It looks though like making a true SVG will take some work and a knowledge of how they're structured, so we can make that a separate issue to be dealt with in the future.

**Comment by HHH-GH** [comment]
> It looks though like making a true SVG will take some work and a knowledge of how they're structured, so we can make that a separate issue to be dealt with in the future.

In the meantime I've replaced the SVG Seed diagram with a PNG file.

I also took a look at what's in Figma.
- The tree (for example) is originally a character in a font. (Maybe an emoji?)
- But do Figma exports (or SVGs in general) allow for custom fonts to be linked or embedded?

Figma exports: looks like image assets are base64-encoded, text/etc vector assets are outlined. (I'm not seeing any font declarations embedded in the SVG I exported from Figma.)

Based on this [post on the Figma blog](https://www.figma.com/blog/with-figmas-new-svg-exports-less-more/) it seems like they're not supporting complicated SVGs.

**Comment by HHH-GH** [comment]
@peth-yursick  Anything else to do on this before I open it for review?

**Comment by peth-yursick** [comment]
> @peth-yursick Anything else to do on this before I open it for review?

Sorry, just seeing this open in my tabs 😅
Just gave it another look, looks great! Thank you 🙏

**Comment by HHH-GH** [comment]
Was advised to tag @luxumbra  for a code review on this.

👋 luxumbra

**Comment by peth-yursick** [comment]
Can we have this reviewed & merged?
Its pretty minor changes on the technical side & currently the Seeds page is displaying false info..

**Review by alalonde — APPROVED** [review]

**Pull request merged**
