### PR TITLE
fix: Setup Header Images

### PR DESCRIPTION
**Pull request by Udit-takkar**
#835

### CODE REVIEW

**Comment by Udit-takkar** [comment]
After Fixing:- 
https://user-images.githubusercontent.com/53316345/134290221-0e384671-c685-4f2d-bad9-106692972f45.mov

**Comment by alalonde** [comment]
Thanks! In the future, you can just push your branch directly to the MetaFam repo. Then Vercel will deploy it automatically

**Comment by dysbulic** [comment]
I'm on the fence on this one. In most places we are using [`BoxedNextImage`](//github.com/MetaFam/TheGame/blob/develop/packages/design-system/src/BoxedNextImage.tsx) to leverage `next/image` without requiring specification of a size in pixels.

The only real downsize is if someone has their screen zoomed `1rem` is not necessarily `16px`. I don't know if that's a big enough need to warrant a change.

**Comment by Udit-takkar** [comment]
@alalonde @dysbulic  any suggestions/changes in this one?

**Review by alalonde — CHANGES_REQUESTED** [review]
Generally speaking, we should aim to use these shared components from the `ds` package as much as possible. Would it suffice in this case?

**Comment by dysbulic** [comment]
@Udit-takkar, so far as how to move forward, the consensus seems to be switch to `BoxedNextImage` out of the `design-system` package.

**Comment by Udit-takkar** [comment]
@dysbulic  ok just saw the package now.

**Comment by Udit-takkar** [comment]
If we use  BoxedNextImage then it would look something like this
Screenshot 2021-09-30 at 11 57 40 PM

To fix we just have to override position : "relative" in 
```
<Box
      {...{ ...props, src: undefined, alt: undefined }}
      style={{
        objectFit: 'contain',
        position: 'relative',
      }}
    >
      <NextImage {...{ src, alt }} layout="fill" objectFit="contain" />
    </Box>
```

**Comment by dysbulic** [comment]
> To fix we just have to override position : "relative" in
> 
> ```
> <Box
>       {...{ ...props, src: undefined, alt: undefined }}
>       style={{
>         objectFit: 'contain',
>         position: 'relative',
>       }}
>     >
>       <NextImage {...{ src, alt }} layout="fill" objectFit="contain" />
>     </Box>
> ```

If you have,
```
<Box
  position="relative"
  objectFit="contain"
  {...props}
>
```
will a definition of `position` in `props` override the setting of `relative`?

**Comment by Udit-takkar** [comment]
> relative

No It didn't

**Comment by Udit-takkar** [comment]
oh fixed now was using props first @dysbulic

**Review by alalonde — APPROVED** [review]

**Pull request merged**
