### PR TITLE
feat: extending global search

### PR DESCRIPTION
**Pull request by Udit-takkar**
## Overview

**What features/fixes does this PR include?**

**Please provide the GitHub issue number**

Closes https://github.com/MetaFam/TheGame/issues/1621

- Added Quests and Patrons

Screenshot 2023-12-16 at 6 09 10 PM

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Comment by alalonde** [comment]
I couldn't test this with quests, but my first test with patrons yielded no results when it should have:

image

**Comment by Udit-takkar** [comment]
@alalonde i created a quest locally to test this.
2) you should be seeing patron result if the query matches name or username of any patron. can you check the network tab if there is an error or maybe try another query string.

**Comment by alalonde** [comment]
> can you check the network tab if there is an error 
Yep, I did, there were just no results.

> or maybe try another query string.
Well, no, because the one I tried should work: "dece" should match decentralion in the screenshot

**Review by Seroxdesign — APPROVED** [review]
LGTM

**Comment by Udit-takkar** [comment]
@Seroxdesign fixed 

Screenshot 2024-01-06 at 7 45 38 PM

**Pull request merged**
