### PR TITLE
Renamed player columns to be consistent snake_case

### PR DESCRIPTION
**Pull request by alalonde**
Also deleted old `timezone` column and renamed `tz` to `timezone`

### CODE REVIEW

**Review by hammadj — COMMENTED** [review]
Noticed there's still some other columns that aren't snake_cased yet, namely:
- EnneagramType
- GuildType
- AccountType
- PlayerRank
- SkillCategory

Do you plan to refactor those in a separate PR?

**Comment by alalonde** [comment]
> Noticed there's still some other columns that aren't snake_cased yet, namely:
> 
>     * EnneagramType
> 
>     * GuildType
> 
>     * AccountType
> 
>     * PlayerRank
> 
>     * SkillCategory
> 
> 
> Do you plan to refactor those in a separate PR?

Those are all enum tables so I left them as they are to distinguish them from the other data tables. I could go either way per renaming them as well.

**Comment by pakokrew** [comment]
I suddenly realised: why renaming the timezone property to `tz` ? I believe you did that because there was an other one and didn't want conflict, but now that the old one is not used anymore, why not calling this one `timezone`? It would be much cleaner like this. Newcomers reading `tz` may be confused

> Those are all enum tables so I left them as they are to distinguish them from the other data tables. I could go either way per renaming them as well.

I am okay to case enums differently from tables, but open to other suggestions than PascalCase form them.

**Comment by alalonde** [comment]
> I suddenly realised: why renaming the timezone property to `tz` ? I believe you did that because there was an other one and didn't want conflict, but now that the old one is not used anymore, why not calling this one `timezone`? It would be much cleaner like this. Newcomers reading `tz` may be confused

That's actually exactly what I've done, it's just a bit confusing due to the diff. `timezone` is the old `tz` column

**Comment by hammadj** [comment]
> Those are all enum tables so I left them as they are to distinguish them from the other data tables. I could go either way per renaming them as well.

Ah ok, makes sense, the differentiation is nice. Approved!

**Review by hammadj — APPROVED** [review]

**Pull request merged**
