### PR TITLE
added analytics

### PR DESCRIPTION
**Pull request by manolingam**

### CODE REVIEW

**Comment by dan13ram** [comment]
@manolingam the vercel bulid failed with the following logs:
```
18:39:20.452 | @metafam/web: Failed to compile.
-- | --
18:39:20.453 | @metafam/web: ./pages/_app.tsx:24:25
18:39:20.453 | @metafam/web: Type error: Cannot find name 'dataLayer'.
18:39:20.453 | @metafam/web:   22 \|       &lt;script&gt;
18:39:20.453 | @metafam/web:   23 \|         window.dataLayer = window.dataLayer \|\| [];
18:39:20.453 | @metafam/web: &gt; 24 \|         function gtag(){dataLayer.push(arguments)}
18:39:20.453 | @metafam/web:      \|                         ^
18:39:20.453 | @metafam/web:   25 \|         gtag('js', new Date());
18:39:20.453 | @metafam/web:   26 \|
18:39:20.453 | @metafam/web:   27 \|         gtag('config', '%NEXT_PUBLIC_GA4_ID%');
18:39:20.485 | @metafam/web: error Command failed with exit code 1.
```

also do we need to add the `NEXT_PUBLIC_GA4_ID` env variable ?

**Comment by alalonde** [comment]
> @manolingam the vercel bulid failed with the following logs:

Yes, probably just need to add the appropriate lib to the tsconfig.json.

> also do we need to add the `NEXT_PUBLIC_GA4_ID` env variable ?

Yeah, he and I already coordinated on this, it's set up

**Comment by manolingam** [comment]
@alalonde & @dan13ram I made a direct push to the repo on a new branch `analytics` for fixing the types locally.
https://github.com/MetaFam/TheGame/tree/analytics

**Comment by alalonde** [comment]
> @alalonde & @dan13ram I made a direct push to the repo on a new branch `analytics` for fixing the types locally.
> https://github.com/MetaFam/TheGame/tree/analytics

I pushed an update, please create a new PR for this new branch into `develop`

**Pull request closed without merging**
