### PR TITLE
New cards

### PR DESCRIPTION
**Pull request by vidvidvid**
## Overview

**What features/fixes does this PR include?**

Updated cards design for:
- [x] players
  - [x] fix badges with XP
  - [x] ~~generated octo avatars (dall e API or stable diffusion (probably an idea for the future))~~
- [x] guilds
  - [x] funding guild / social guild tags?
  - [x] barrier of entry
  - [x] skills
- [x] role paths
  - [x] Design
  - [x] Pictures
  - [x] Difficulty of the Role Paths
  - [x] Time needed for Role Paths
- [ ] #752 
- [x] patrons
  - [x] reuse player cards
  - [x] update the xp flag with $
- [ ] quests
  - [x] design
  - [x] disable the js tilt in the quest view 
  - [ ] #1446 

Issues:
- [x] Fix the `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.` in cards. This happens because the whole card is wrapped into a link & there are more links inside of it.

**Please provide the GitHub issue number**

Closes #

## Implementation

Used [vanilla-tilt](https://www.npmjs.com/package/vanilla-tilt) package for the hover effect.

#### Design:
https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=6701%3A6415

#### Preview:
https://user-images.githubusercontent.com/35112939/200346493-db98eeed-9d79-4c90-98a6-c03d9d43515d.mov

### CODE REVIEW

**Comment by peth-yursick** [comment]
As requested, some issues:
image
- [ ] All profile photos should be the same size square, cropped when necessary
- [ ] The photo part & text part should all be same size on all cards
- [ ] "Contact" & "member of" should always be displayed at the bottom of the card & "skills" should also always float on the same part of the card regardless of how big the bio is, whether it exists or not etc.
- [ ] Should be using emojis instead of the "diamond"
- [ ] All card starting in row 4 have this weird white glow when hovering the bottom part of the card
   - image
- [ ] If you hover the top part of the bottom row cards & scroll while hovering, the effect stays "locked" on the top part hover even after moving the mouse to the bottom part of the card
- [ ] The whole cards should be clickable, currently the outer margins of a card aren't (actually on players they aren't but on patrons looks like they are wholly clickable - patrons have a different problem tho)
- [ ] Patrons page is marked as complete but looks more like the old version to me
   - image
- [ ] Guilds are only displaying MCV & MetaFam for some reason with MetaFam image broken
   - image
- [ ] The join button should be removed so people open the pages before going to their website
- [ ] Should also all be same size & proportions regardless of image dimensions, amounts of text etc.
- [ ] Also outer margins of the card not clickable

That's all I'm seeing right now but also probably more than enough 😂

**Comment by luxumbra** [comment]
> Should be using emojis instead of the "diamond"

I'd also add that in the Figma, these bits are square aspect.

From a design perspective, I kinda feel the radius on corners of elements *inside* the cards (cut out, title, etc) should match - 10px feels too heavy for the card title. 
image

**Comment by vidvidvid** [comment]
> Overall, all cards be same size & proportions regardless of image dimensions, amounts of text etc.

I can make all of the cards in the same row the same size - that's the simplest solution. Also the differences between rows won't be noticeable, i'd prefer not to make the height and width static.

**Comment by peth-yursick** [comment]
> From a design perspective, I kinda feel the radius on corners of elements _inside_ the cards (cut out, title, etc) should match - 10px feels too heavy for the card title.

Agreed, all edges are rounded at 10, now rounded the inner square & membership/contact squares to 7, looks a bit better
image

> I can make all of the cards in the same row the same size - that's the simplest solution. Also the differences between rows won't be noticeable, i'd prefer not to make the height and width static.

Yeah, I don't think the size should be static in terms of actual pixels, just the proportions of each part in relation to others, if that makes any sense 😂
What do you mean the difference between rows won't be noticeable?

**Comment by vidvidvid** [comment]
@peth-yursick 
> Guilds are only displaying MCV & MetaFam for some reason with MetaFam image broken

also in the testing env the img is broken, but it should be visible in production.
https://test.metagame.wtf/guilds

**Review by luxumbra — COMMENTED** [review]
Looking sweet @vidvidvid but I still find the contrast on player names is less than ideal where folks have lighter avatars. I think a darker color...perhaps `landingGlassDark` would work better for the bg of the name. 
image

I also feel the text in the insets should be white or at least lighter to improve contrast now that the bg is darker.
image

**Comment by vidvidvid** [comment]
@luxumbra oukidouki, i will fix that. btw what is that addon which shows you the contrast?

**Review by dysbulic — APPROVED** [review]
Looks reasonable to me given the changes that are in #1448 to some stylistic issues.

**Comment by vidvidvid** [comment]
@luxumbra @dysbulic i fixed your suggestions! :)

**Pull request merged**
