### PR TITLE
Use Plausible for data tracking

### PR DESCRIPTION
**Pull request by vidvidvid**
## Overview

**What features/fixes does this PR include?**

Add Plausible analytics.

Screenshot 2023-05-19 at 17 14 10

### CODE REVIEW

**Comment by dysbulic** [comment]
@vidvidvid, should Plausible be deployed on the test and development instances?

Rather than wrapping `App` in `PlausibleProvider`, you could wrap `DeployedApp` and it would only affect `production`.

**Comment by vidvidvid** [comment]
> @vidvidvid, should Plausible be deployed on the test and development instances?
> 
> Rather than wrapping `App` in `PlausibleProvider`, you could wrap `DeployedApp` and it would only affect `production`.

This library already makes sure that plausible activates only in production.

**Comment by dysbulic** [comment]
> This library already makes sure that plausible activates only in production.

@vidvidvid, when `next build` is run, as it is for the test instances, `NODE_ENV` is set to `production` even though it's not really the production server. There's no way to change this.

Is `NODE_ENV` what Plausible is using to determine the environment?

**Comment by vidvidvid** [comment]
@dysbulic i did as you suggested

**Review by dysbulic — APPROVED** [review]
Seems reasonable to me.

You should include a link to these statistics somewhere. If nothing else, start a new document in `guides/`.

**Pull request merged**
