### PR TITLE
Squashed Adding of an Image to Quests

### LINKED ISSUE #1446: Add pictures to quests
### What would you like to be added?

- [ ] In the quest creation screen, please add a field for adding a picture to the quest.
- [ ] It would be great if editing of quests would include editing of their respective picture.

### Why is this needed?

It is needed in #1443 & consequently in the #1438 PR .

### PR DESCRIPTION
**Pull request by dysbulic**
This request is a squashed version of #1448 by @thebeyondr. The original request was:

## Overview

This adds:
- The ability to add images when creating a quest
- Image preview on the form (wasn't in the issue but it just made sense 🤷‍♂️)
- Updated spacing of form items
- Quest image upload to `web3.storage`

Closes #1446, #1465, #1466, & #1467.

## Follow-Up Improvement Ideas

- Create greater contrast between form and background. Form labels are sometimes hard to read.

## Side Effects

- The `image` property that is stored on the quest is returned as `ipfs://` so retrievers will need to use the `httpLink` helper when accessing `quest.image` to receive a URL to be used in `<Image src=*/>`

- Fixing a hydration error currently present in `develop` as well as a misconfiguration of `NODE_ENV` for the test instances was necessary to properly test this PR.

## Attributions

* Paired-With: @thebeyondr

### CODE REVIEW

**Comment by vidvidvid** [comment]
looks great! :) i tested creating a quest & editing the quest image. both work, great job!

**Comment by vidvidvid** [comment]
could you also please change the description in phase 3 in raids so we don't have to open a new PR just for this? 😅 we missed that:
image

It should have this text:
```
Zoom out of Web3, include other high impact technologies & focus more on regenerative projects in the real world as well as helping people live optimally.
```

Figma: https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=7011%3A6935&t=ibBDe0CZBjIB4mEU-0

**Comment by thebeyondr** [comment]
> could you also please change the description in phase 3 in raids so we don't have to open a new PR just for this? 😅 we missed that

Done ✅

**Comment by vidvidvid** [comment]
is anything still missing from this PR?

**Comment by dysbulic** [comment]
> [O]n the quest cards that the font size & line height on the quest titles is a little extreme

@luxumbra, I dropped the line height. I didn't drop the size because going from `lg` to `md` made the heading the text the same size as the body text & it didn't look as headery.

> [T]he description heading & the title could do with a bit more white space between them.

I padded the bottom of the header, scooched it down a bit, & clamped the lines at three just in case someone goes nuts with a long title.

> [C]ould we swap them [`p`s] out for `h3`[s] as they aren't paragraphs but mini headings.

I switched the tags to <TileHeading>` = `<Text as="h3">` because using `Heading`s changed the color and font.

Screenshot from 2022-12-06 15-15-38

Also on the details page I use the same `TileHeading` component. Also, I centered the image and title.

Screenshot from 2022-12-06 15-21-03

**Comment by luxumbra** [comment]
> I padded the bottom of the header, scooched it down a bit, & clamped the lines at three just in case someone goes nuts with a long title.

Looks way better. The description text seems a bit on the large size or is that just me?
image

**Comment by dysbulic** [comment]
> Looks way better. The description text seems a bit on the large size or is that just me?

@luxumbra, it looks ok to me, but I use big fonts in general. I've got both my OS & browser base font size kicked up 115%.

I'm pretty sure there's a bug where if a quest has no roles it will silently fail to save, but I'm going to create an issue for that and deal with it elsewhere since it's not central to this PR.

**Comment by luxumbra** [comment]
> > Looks way better. The description text seems a bit on the large size or is that just me?
> 
> I've got both my OS & browser base font size kicked up to 115%.

That would  explain it. 😄

**Review by luxumbra — APPROVED** [review]
LGTM

**Pull request merged**
