### PR TITLE
Feature/mobile select roles

### LINKED ISSUE #311: [MyMeta] Add the role selection screen to the profile creation flow
Currently, role selection is done through a Discord bot. We want to add it to the profile creation flow (Connect button [here]( https://my.metagame.wtf/players)). 

We probably want new tables such as `guild_role` and `guild_player_role` to store these new roles. This should support guilds that have a discord integration as well as those that do not. 

Ideally, choosing roles would also apply the appropriate Discord role. For this to work, we'd first need to know a player's discord ID, which we could ask for in a prior step.

### PR DESCRIPTION
**Pull request by alalonde**
## Overview

**What features/fixes does this PR include?**

Mobile version of role selection during the onboarding wizard.

Closes #311

### CODE REVIEW

**Review by vidvidvid — COMMENTED** [review]
Looks very nice, while browsing through the steps I noticed one inconsistency and a possible visual improvement that could be made.
The inconsistency is in the appearance of the menu at the top, which is is not displayed constantly throughout the setup screens:
menu

And a possible visual improvement could be made by making a constant width for all personality types:
type

These remarks don't necessarily have to be solved in this issue, but you might wanna consider doing that along the way if you're already at it.

**Comment by Udit-takkar** [comment]
> Looks very nice, while browsing through the steps I noticed one inconsistency and a possible visual improvement that could be made. The inconsistency is in the appearance of the menu at the top, which is is not displayed constantly throughout the setup screens: menu
> 

I think this is due to the hideTopMenu Prop being passed in these components

```
export const getStaticProps = async () => ({
  props: {
    hideTopMenu: true,
  },
});
```

**Review by dan13ram — APPROVED** [review]
Great stuff. 

I have a small question though, I'm unable to find a way to go to `/profile/setup/roles` unless i type that url directly. Is this a feature that only new players who go through the setup process can edit their roles ?

**Comment by Udit-takkar** [comment]
> I have a small question though, I'm unable to find a way to go to `/profile/setup/roles` unless i type that url directly. Is this a feature that only new players who go through the setup process can edit their roles ?

Currently it is not available to anyone. to access it `/lib/hooks/index` . Comment out ` if (!redirectTo) return;` in useUser.

**Comment by alalonde** [comment]
Yes, we have a separate edit profile UI now, check it out on test.metagame.wtf

**Pull request merged**
