### PR TITLE
Onboarding Guidance Page

### LINKED ISSUE #1444: The onboarding guidance screen
### What would you like to be added?

I would love there to be an onboarding guidance screen to give people a view of how onboarding into MetaGame works before they start going through the whole process of completing the Engaged Octo path etc.

Wrote this for the newsletter then designed it into a page:
image
[Figma file](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=4143%3A1628)

- [x] This screen should appear between the onboarding game & the mymeta profile creation. If possible, this should be using the same cards template that @vidvidvid implemented for #1443
After that (these will be separate issues once this one is completed):
- [ ] The game should detect either when a player has gained the Engaged Octo role on MetaGame's discord or when their Engaged Octo path has been approved as completed, then present them with the same screen but showing their progress
- [ ] Then, once again when they become a player or patron, it should show something similar, congratulate them & show them the "welcome to metafam" page
- [x] After that, I will design a follow up screen that displays next stages..

### Why is this needed?

Right now people are put directly through the mymeta profile creation & then onto the engaged octo path without gaining a context on how joining MetaGame actually works.
Giving them an overview like this will help them understand & make them more motivated to continue their joining journey.

### PR DESCRIPTION
**Pull request by nitegeist**
## Overview

**What features/fixes does this PR include?**
* Layout for onboarding guidance page
* New card designs featured in [MetaOS] Updating the cards design #1443
* `Join as a player` & `Join as a patron` links to redirect to onboarding guidance page
* Images for curious octo and space octo roles

**Please provide the GitHub issue number**

Closes #1444.

## Follow up Improvement Ideas

- [ ] Create enum for player roles to determine what role a player has from discord and what route to redirect to after a user clicks `Join as a player` or `Join as a patron`
## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**
* Uses new card designs by @vidvidvid

## Assets

Design: [Figma Design](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=4143%3A1628)

### CODE REVIEW

**Comment by nitegeist** [comment]
I creaated this new PR because the previous one from a fork and the test instances won't build for foreign forks so reviewers weren't able to see what my changes looked like.

**Review by vidvidvid — CHANGES_REQUESTED** [review]
A couple of corrections & we should be good to go:
1. Please add a margin/padding on the bottom of the page
Screenshot 2022-11-18 at 21 00 40

2. On mobile please fix the top of the page so that the cards don't overlap with the menu & make a smaller padding on the sides of the cards so the text won't be so squished anymore.
Screenshot 2022-11-18 at 21 01 02

3. `You are here` text is not visible and not centred.
Screenshot 2022-11-18 at 21 01 05

**Comment by nitegeist** [comment]
> A couple of corrections & we should be good to go:
> 
> 1. Please add a margin/padding on the bottom of the page
> 
> Screenshot 2022-11-18 at 21 00 40
> 
> 2. On mobile please fix the top of the page so that the cards don't overlap with the menu & make a smaller padding on the sides of the cards so the text won't be so squished anymore.
> 
> Screenshot 2022-11-18 at 21 01 02
> 
> 3. `You are here` text is not visible and not centred.
> 
> Screenshot 2022-11-18 at 21 01 05

These changes have been implemented in my latest commit

**Review by vidvidvid — APPROVED** [review]
Lovely, thank you for the corrections! :)

**Pull request merged**
