### PR TITLE
feature/search-functionality

### PR DESCRIPTION
**Pull request by phys3**

### CODE REVIEW

**Comment by alalonde** [comment]
Is this ready? In the preview I can't even focus into the search bar

**Comment by phys3** [comment]
> Is this ready? In the preview I can't even focus into the search bar

it is not ready, need to start working on it

**Comment by alalonde** [comment]
OK, it is helpful to have your work pushed in order to signal what's being worked on. One thing we try to do is mark PRs as drafts (link in the right sidebar) so reviewers can ignore it

**Comment by Udit-takkar** [comment]
@phys3  do you plan to finish this one?

**Comment by phys3** [comment]
> @phys3 do you plan to finish this one?

will do was a bit busy with other stuff and kinda forgot about it, if its cluttering prs we can close it and ill reopen when finished

**Comment by luxumbra** [comment]
> > @phys3 do you plan to finish this one?
> 
> will do was a bit busy with other stuff and kinda forgot about it, if its cluttering prs we can close it and ill reopen when finished

We are really trying to push progress forwards on outstanding issues & PRs and have a bunch of folks eager to pick up work. As this has been sitting for ~3 months, if you're unable to get to it in the next couple of days @phys3, it would be really cool if you'd pass the baton to @Udit-takkar. Either way, would be brilliant to see this finished. 🙏🏻

**Comment by phys3** [comment]
> > > @phys3 do you plan to finish this one?
> > 
> > 
> > will do was a bit busy with other stuff and kinda forgot about it, if its cluttering prs we can close it and ill reopen when finished
> 
> We are really trying to push progress forwards on outstanding issues & PRs and have a bunch of folks eager to pick up work. As this has been sitting for ~3 months, if you're unable to get to it in the next couple of days @phys3, it would be really cool if you'd pass the baton to @Udit-takkar. Either way, would be brilliant to see this finished. 🙏🏻

@Udit-takkar you can take this, ill be back in 2 weeks

**Comment by Udit-takkar** [comment]
@luxumbra  Is there any design or notion file for this? 
Just searching players feature has to implemented like on the players page ?

**Comment by luxumbra** [comment]
> Just searching players feature has to implemented like on the players page ?

I will find out for you @Udit-takkar I can't see any other info on it, other than #849, which as you probably noticed, doesn't have much info. 

@davort or @peth-yursick is there a design or spec for the Search?

**Comment by luxumbra** [comment]
> @luxumbra Is there any design or notion file for this? Just searching players feature has to implemented like on the players page ?

@Udit-takkar I have asked for info in designers guild

**Comment by davort** [comment]
Hey @Udit-takkar and @luxumbra - let me get back to you tomorrow on this. Thank you for your patience 🙏

**Comment by davort** [comment]
Touched base with @Udit-takkar on [Discord](https://discord.com/channels/629411177947987986/782054676546846752/918120690148868136). 

**The initial plan**
> So when a user searches a player name from the navbar. He would be redirected to /players and would be shown results based on that search query."

I updated the Forum thread accordingly, with some more context on the broader plan for the Search functionality: https://forum.metagame.wtf/t/global-search-in-mymeta-ui-making-it-work-across-the-metagame-universe/720/

**Comment by Udit-takkar** [comment]
I am guessing i would have to build a context with the searched name to be able to display search results on the `/players` page

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/145465785-5840858c-668c-430f-8e25-75003d105d08.mov

Just trying some test implementations. @dysbulic  @vidvidvid  any suggestions?

**Comment by vidvidvid** [comment]
Nice stuff, just add a big fat spinner or some kind of indicator that stuff is being fetched (and maybe block other interactions with the UI in the meantime).

**Comment by Udit-takkar** [comment]
> Nice stuff, just add a big fat spinner or some kind of indicator that stuff is being fetched (and maybe block other interactions with the UI in the meantime).

Okay. so the desired outcome later is to be able to search everything. For that I am guessing we would have to create a separate page

**Comment by alalonde** [comment]
It seems that the design for search results is forthcoming, but I am assuming we will have a generic "search results" page which shows the results by category, e.g. patrons, players, etc. 

The current implementation is really just "search players from the menubar" which is not especially useful. I would like to see in this first implementation:

- search players
- search patrons
- search guilds
- search internal page names

Where the results are shown in a separate page which displays immediately upon hitting "enter". For instance, if I search for "Meta" I would expect to see a few players, a few guilds, and a few patrons. 

And if I search for e.g. "Seed" it would show two results for URLs in the megamenu: "Seed" and "Balancer Pool", matching either the menu's title or description.

So obviously there's a lot more here. 

If we want to go ahead with this placeholder implementation, I think we would want to change the placeholder to "search players" and at least show a spinner. But ideally we at least have that separate search results page.

**Comment by davort** [comment]
@alalonde – makes sense. I will design a simple Search UI today, to accommodate for these different search result types you listed. We can then take it from there, and see what of that can easily be built. But the main goal is to establish a proper Search workflow already at this step, if feasible. Back soon with some designs! 👋

**Comment by Udit-takkar** [comment]
> It seems that the design for search results is forthcoming, but I am assuming we will have a generic "search results" page which shows the results by category, e.g. patrons, players, etc.
> 
> The current implementation is really just "search players from the menubar" which is not especially useful. I would like to see in this first implementation:
> 
> * search players
> * search patrons
> * search guilds
> * search internal page names
> 
> Where the results are shown in a separate page which displays immediately upon hitting "enter". For instance, if I search for "Meta" I would expect to see a few players, a few guilds, and a few patrons.
> 
> And if I search for e.g. "Seed" it would show two results for URLs in the megamenu: "Seed" and "Balancer Pool", matching either the menu's title or description.
> 
> So obviously there's a lot more here.
> 
> If we want to go ahead with this placeholder implementation, I think we would want to change the placeholder to "search players" and at least show a spinner. But ideally we at least have that separate search results page.

Okay I'll add these functionalities

**Comment by davort** [comment]
@Udit-takkar & @alalonde — need your feedback, when you find a moment. Here's a quick and dirty prototype: https://tinyurl.com/y3aa4w8n

The idea is for us to first align on the basic workflow for Search:

1. Type in a phrase (partial or full)
2. Show "top 3" results as the user is typing, with additional links to show "all results"
3. All results show all results, per category

If this workflow seems OK to you, I would like to go back to the designs and tighten them up a bit. Mostly in terms of layout, but also feel free to suggest adding something in, or dropping something out.

Question: for "all results", would it make sense to show the sort & filter UI, such as we have for https://my.metagame.wtf/players ?

**Comment by Udit-takkar** [comment]
I have not implemented search functionality for scale. so Probably @alalonde  or @mquellhorst could answer what could be implemented. Michiel also mentioned we probably would have to use Elastic Search for this. 
https://medium.com/@gunar/sync-postgres-and-elasticsearch-with-hasura-today-e234086d338

**Comment by alalonde** [comment]
> I have not implemented search functionality for scale. so Probably @alalonde or @mquellhorst could answer what could be implemented. Michiel also mentioned we probably would have to use Elastic Search for this. https://medium.com/@gunar/sync-postgres-and-elasticsearch-with-hasura-today-e234086d338

Yeah I don't think we need to at this point in time. We really don't have a lot of data at this moment. https://hasura.io/blog/full-text-search-with-hasura-graphql-api-postgres/

**Comment by alalonde** [comment]
> @Udit-takkar & @alalonde — need your feedback, when you find a moment. Here's a quick and dirty prototype: https://tinyurl.com/y3aa4w8n
> 
> The idea is for us to first align on the basic workflow for Search:
> 
>     1. Type in a phrase (partial or full)
> 
>     2. Show "top 3" results as the user is typing, with additional links to show "all results"
> 
>     3. All results show all results, per category
> 

I'm not sure our search would be fast enough to show partial results quickly enough to be useful. Search is rather difficult and users have high expectations thanks to Google :)

I do like that dropdown though, it would be cool if we could make use of it.  What would the mobile version be?

> If this workflow seems OK to you, I would like to go back to the designs and tighten them up a bit. Mostly in terms of layout, but also feel free to suggest adding something in, or dropping something out.
> 
> Question: for "all results", would it make sense to show the sort & filter UI, such as we have for https://my.metagame.wtf/players ?

Within a given tab, yes, I think so.

**Comment by Udit-takkar** [comment]
@davort  Is the design ready for this?

**Comment by davort** [comment]
Hey @Udit-takkar!
I believe it's nearly finished. Just needs me to design the mobile variants, across all breakpoints, and we should be good to go.
I will aim to have that done in the next couple of days (Mon or Tue).

**Comment by Udit-takkar** [comment]
Closing this as this one has lot of messages and it might get confusing. 
Would raise another PR

**Pull request closed without merging**
