### PR TITLE
Fixed guild member sync

### LINKED ISSUE #1239: [Guilds] Guild member sync is broken
### What happened?

I approved TEC's guild application, which should have triggered a sync where we associate their members from Discord with our players.  This did not happen.

### What did you expect to happen?

 A sync

### How can we reproduce the problem (as minimally as possible)?

Go to https://metagame.wtf/guild/TEC. You can also trigger a sync through the hasura console.

### Is there anything else we need to know?

_No response_

### Browser and operating system used (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by alalonde**
## Overview

**What features/fixes does this PR include?**
Closes #1239

I also got backend debugging working locally, so I created a gist and linked to it in the README.

## Follow up Improvement Ideas

- [x] Fix the bot such that it posts a message to the props channel. 
- [ ] Requires implementing #1240 first

### CODE REVIEW

**Comment by alalonde** [comment]
@polimyl I adjusted our docker-compose.yml with the assumption that is only used locally; is that an accurate assumption?

**Comment by polimyl** [comment]
@alalonde im not aware of any uses of the docker-compose outside of local development

**Comment by alalonde** [comment]
@dysbulic @polimyl @dan13ram Please review

**Comment by alalonde** [comment]
Just tested the code that posts rank advancements to the give-props channel, and it worked. I just needed to give the bot access to that channel.

**Pull request merged**
