### PR TITLE
feat: make player card clickable

### LINKED ISSUE #343: [MyMeta] Make the whole Player card clickable
On My Meta homepage make the whole player card clickable so that it is easier to access the player profile page.
Current behavior: Player name is a link (clickable)
New behavior: Player Card is a link (clickable)

### PR DESCRIPTION
**Pull request by sunguru98**
This is my attempt to make the whole player card clickable. I haven't removed the player name feature yet, because a lot of content is above the card and there isn't much of empty space. But I'm game with whatever thoughts is :) 

Closes #343

### CODE REVIEW

**Comment by dan13ram** [comment]
@sunguru98 The `develop` branch was force-pushed, could you please rebase with the latest `develop`

**Comment by sunguru98** [comment]
Sure will .. On it right now :) @dan13ram

**Comment by sunguru98** [comment]
Donezo @dan13ram

**Comment by alalonde** [comment]
Looks pretty good; my only suggestion would be to perhaps add a hover state or something on the card that indicates that clicking it will do something? There isn't a whole lot of click area on a particular card.

**Comment by sunguru98** [comment]
Makes sense @alalonde .. will add that up :)

**Comment by alalonde** [comment]
> Makes sense @alalonde .. will add that up :)

Also please see @davort's comments in #343

**Comment by dan13ram** [comment]
Closing in favor of #727

**Pull request closed without merging**
