### PR TITLE
Feature/ens data

### PR DESCRIPTION
**Pull request by Seroxdesign**
## Overview

**What features/fixes does this PR include?**

**Please provide the GitHub issue number**

Closes #

## Follow up Improvement Ideas

- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Comment by alalonde** [comment]
Why is dysbulic's commit in this PR?

**Comment by alalonde** [comment]
Don't worry about the test deployment, your code should just match the other PR. When it gets deployed to the test env it should just work, and if not we can fix it there

**Comment by Seroxdesign** [comment]
> Don't worry about the test deployment, your code should just match the other PR. When it gets deployed to the test env it should just work, and if not we can fix it there

@dysbulic is helping me on some core Hasura stuff that's important for the feature to work in develop/main.

He's going to be reviewing the code soon as well

**Comment by dysbulic** [comment]
> Why is dysbulic's commit in this PR?

@Seroxdesign imported my modified GitHub Action and in order for it to work Hasura and the seeding script needed to be updated. Rather than explain it, I did the work myself.

**Comment by dysbulic** [comment]
@alalonde, I think you might think I'm picking nits, but this code needs some attention before we should be merging it into `develop`.

https://user-images.githubusercontent.com/181523/221329734-55cfb9e8-3209-446a-a850-fbba8a7bc299.mp4

**Comment by dysbulic** [comment]
Here's another example. Again, it is taking over ten seconds for my display name to appear because the ENS lookups are putting all the name resolutions on hold.

I don't know the exact solution. Something with `Promise`s probably, but as it stands this PR affects the usability of the site.

https://user-images.githubusercontent.com/181523/221330720-b731f5f8-7b10-4df6-87d3-008cfe08e796.mp4

**Comment by Seroxdesign** [comment]
@dysbulic happy to fix this, do you have any recommendations?

When we have to lookup multiple names like in leaderboard or players we need to look up all addresses we display which will take time since it's asyn

I can avoid looking up names if user has a username, that could help?

**Comment by Seroxdesign** [comment]
https://user-images.githubusercontent.com/69639595/221377947-7eae25f6-e12c-45f3-b9a2-30f62f9f28e0.mp4

Resolved @dysbulic

**Comment by alalonde** [comment]
> @alalonde, I think you might think I'm picking nits, but this code needs some attention before we should be merging it into `develop`.

Yes, 100% agree.  I was expecting code style nits, but these are very substantial issues. Appreciate the diligence 🙏

**Review by dysbulic — APPROVED** [review]
Fuck it. I'm tired of reading this & don't think it's going to explode or anything.

**Pull request merged**
