### PR TITLE
Sero/starting button - Ready for review

### PR DESCRIPTION
**Pull request by Seroxdesign**
## Overview

**What features/fixes does this PR include?**

- Improves landing page UX
- Add substack mailing list form

**Please provide the GitHub issue number**

https://linear.app/metagame/issue/MG-13/add-players-guilds-patrons-and-advisors-section

Closes #

https://linear.app/metagame/issue/MG-13/add-players-guilds-patrons-and-advisors-section

## Follow up Improvement Ideas

- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Comment by alalonde** [comment]
What is the purpose of this? What issue does it resolve?

**Comment by Seroxdesign** [comment]
> What is the purpose of this? What issue does it resolve?

Untitled

I added a mailing list join for the substack, and removed a button/changed language for improved UX @peth-yursick can fill in more details

**Comment by peth-yursick** [comment]
> What is the purpose of this? What issue does it resolve?

Currently, there are 2 buttons:
"join" - takes people through the onboarding game, mymeta profile creation & onboarding quests
"watch" - takes people directly to the dashboard, leaving them utterly confused

Cami did some user research, realized most people click "watch" first, get confused & leave.

New version: 
Replaces the "watch" button with newsletter subscription, for those who arent ready to jump straight in + fulfills the goal of growing the subscription list
Retitles "join" into "check it out" which doesnt imply investing a significant amount of time since the first step is just clicking through the onboarding game to see if you like it

CTA had also been significantly improved, replacing the one with V for Vendetta reference which most people didnt get

**Comment by alalonde** [comment]
OK, please add a link to the relevant Github issue or Dework task so reviewers have some context. We have a PR template for a reason ;)

**Comment by Seroxdesign** [comment]
> OK, please add a link to the relevant Github issue or Dework task so reviewers have some context. We have a PR template for a reason ;)

https://linear.app/metagame/issue/MG-13/add-players-guilds-patrons-and-advisors-section

**Review by alalonde — APPROVED** [review]

**Pull request merged**
