### PR TITLE
Fix/1408 - Make Guild Links Prominent Again

### LINKED ISSUE #1408: [Guilds] Making links more prominent
As I was going through all twitter profiles of guilds so I can manually create guild pages & update existing ones before the launch, I've noticed a lot of them are using Linktree - some even as their default link..

Thinking:
If we make the link buttons bigger/more prominent, we could try to get these guilds to replace their Linktrees with their guild profiles in their bios. As a bonus, it would make profiles less bare as a lot of them dont have much yet.

Initial design:
image

Thoughts? @davort @alalonde

### PR DESCRIPTION
**Pull request by thebeyondr**
## Overview

**What features/fixes does this PR include?**
This updates the design of the social links on the guilds page

**Please provide the GitHub issue number**
Closes #1408 

## Follow up Improvement Ideas

- [x] One background image instead of two

## Implementation

**Side effects**
- Grid layout has changed

## Assets
image

### CODE REVIEW

**Comment by alalonde** [comment]
Hmm, this didn't deploy for some reason. Also there's a conflict now

**Comment by thebeyondr** [comment]
|image|
| --- |
| Screenshot as of last commit |

**Comment by thebeyondr** [comment]
> Hmm, this didn't deploy for some reason. Also there's a conflict now

@alalonde I refactored a file that's now in conflict — should be safe to merge though

**Comment by alalonde** [comment]
> I refactored a file that's now in conflict

That may be true but it was not pushed!

**Review by alalonde — APPROVED** [review]
My only beef with this is now any contract addresses are showing up under "Social" which doesn't make any sense:
image

But that's probably a separate issue

**Comment by alalonde** [comment]
> [Merge branch 'develop' into fix/1408-guilds-making-links-more-prominent](https://github.com/MetaFam/TheGame/pull/1507/commits/d6873e68642e819a5ffbd4c858e7ae93d586803e)

Looks like you did a merge, not a rebase. You will have to rebase `git rebase develop` instead

**Comment by thebeyondr** [comment]
> My only beef with this is now any contract addresses are showing up under "Social" which doesn't make any sense

100% agreed.

**Pull request merged**
