### PR TITLE
Fix mobile connect

### LINKED ISSUE #338: [MyMeta] Error reconnecting with Metamask after an initial connection with WalletConnect
> [Davor]: [I'm] connecting with MetaMask and this screen pops up whenever I load a new page on my.metagame.wtf
> 
> 
> 
> But can't seem to get past it. … I hit the "Sign" button, but then nothing happened after that ☹
> 
> [The error console when I attempt to sign is:]
>
> Screenshot_20210209
>
> I remembered that the first time I tried this, I used the Argent app, FWIW. But even then, I didn't get any feedback from the website whatsoever

It looks to me like Web3Modal has cached WalletConnect and is attempting to use it. Why the Metamask dialog is coming up, I don't know.

Adding `modal.clearCachedProvider()` to the `Disconnect` action should be done.

This doesn't fix Davor's issue since he can't connect.

### PR DESCRIPTION
**Pull request by pakokrew**
Trying to fix #338 

Need someone to try it out

### CODE REVIEW

**Comment by dysbulic** [comment]
The profile isn't showing up when using WalletConnect some of the time.


https://user-images.githubusercontent.com/181523/108678628-52b07580-74b9-11eb-9abe-0e36f7a2efa5.mp4

**Comment by pakokrew** [comment]
> The profile isn't showing up when using WalletConnect some of the time.> 

Thanks for trying it.
I've improved it a little bit, what do you see now ?

**Comment by dysbulic** [comment]
I'm seeing quite a few different things that I've got no good explanation for (other than caching somewhere):

https://user-images.githubusercontent.com/181523/109064055-e6e82b80-76b7-11eb-8eef-a88cf8034680.mp4

**Comment by pakokrew** [comment]
> I'm seeing quite a few different things that I've got no good explanation for (other than caching somewhere):
> 
>  2021-02-24.15-45-30.mp4

The first problem you mention here was already present, and due to the fact that we do not handle account change on the provider. This PR was about fixing connecting on mobile phones browsers. If you don't mind I would prefer open another issue&pr.

For the second one, I'll investigate...

**Comment by dysbulic** [comment]
> For the second one, […] I can't reproduce the error, even when trying with account not registered yet. Nothing in the console?

I wish I had something productive to report. Under Ubuntu in both Chrome and Firefox, I open a new incognito window – which should have no saved settings – and the profile disappears after I authenticate and sign the wallet connect message.

The only thing in the console is "`wallet connect`".

**Comment by dan13ram** [comment]
Hey @pakokrew I did a round of testing and still find issues when disconnecting and connecting with a new account.
https://www.loom.com/share/d90b0f7885ba4ffca365f9ec8e4b09cf

**Comment by dysbulic** [comment]
I ran upon this issue trying to test out some mobile fixes to the site. I spent a few hours debugging and my guess is that one of the main issues has to do with signature verification via WalletConnect. [All of the wallets seems to be broken in one way or another.](https://github.com/WalletConnect/walletconnect-monorepo/issues/347#issuecomment-798782047)

I couldn't get a profile to display using Argent which can't generate valid signatures, but things worked with Trust Wallet easily enough.

I suspect the problem is not being able to validate the `authToken`.

**Comment by pakokrew** [comment]
Just seeing your comments now.

There are two major distincts issues here:
- Handling when user changes account in wallet
- Signing with contract-based wallets such as Argent

I'll try to answer these two issues separately

**Comment by pakokrew** [comment]
Just found that the issue of connect/disconnect/reconnect with another account is not coming from this Web3Context, but from the urql setup we have. 
We need to rewrite how we manage the authentication token inside `withUrql` in _app

If you don't mind, I'd prefer merge this @dan13ram @dysbulic then work separately on handling account change from provider and better setting up urql. There's already an issue for the first on, I'll create another one for the send.

**Comment by pakokrew** [comment]
Ok I found a quick fix that resolves the issue with URQL when explicitely disconnect and reconnect with another account.

**Review by dan13ram — APPROVED** [review]
As you said, lets merge this so we can fix the address issue in a separate PR.

Looks like there is a lint issue, though. Please fix that before merging!

**Pull request merged**
