### PR TITLE
[MyMeta] Add Architecture Diagram

### PR DESCRIPTION
**Pull request by dysbulic**
This pull request adds an architecture diagram I did and a few minor edits to the documentation.

### CODE REVIEW

**Comment by dysbulic** [comment]
This pull request was created by overwriting a bunch of files with the version from `develop`. Then it was rebased.

Somehow that causes the number of changed lines to show as 4k+, but it is, in actuality, not very long.

**Comment by mquellhorst** [comment]
The PR is still a draft tho.
Aren't these commits shown from the ceramic branch?

**Comment by mquellhorst** [comment]
I just  looked in the branch for ceramic login and noticed these documentation changes are in there as well

**Review by Cali93 — APPROVED** [review]
I love the svg ! Good job

**Review by mquellhorst — APPROVED** [review]

**Pull request merged**
