### PR TITLE
Change the default share image for OpenGraph and Twitter cards

### LINKED ISSUE #1450: Change the default sharing embed image
Right now, sharing the links in telegram displays this extremely cringe old logo I made 3 years ago that got replaced over a year ago:
image

It should be replaced with this image:
image

### PR DESCRIPTION
**Pull request by HHH-GH**
## Overview

**What features/fixes does this PR include?**

Changes the default image that's used for shares via Twitter/Telegram/Facebook/etc. 

**Please provide the GitHub issue number**

Closes #1450

### Add the new image in packages/web/public/assets
I put the share image in /packages/web/public/assets so Next will serve it as a static asset from /assets (no need for a hostname in front, so it can be tested locally and from the PR deployment)

### Update the default canonical URL to match current scheme used on the site i.e. `metagame.wtf` instead of `my.metagame.wtf`
No comment - assume this is ok

### Bit of commenting around usage of HeadComponent
Usage/suggestions

## Also
This is the new image.

MG-share-image_octopus-in-space

I also found another share image, currently in use on the landing page.

landing-social

### CODE REVIEW

**Comment by HHH-GH** [comment]
I'll test it actually works after it deploys ...

**Comment by HHH-GH** [comment]
Works with Facebook shares, will assume it's all go with Twitter/Telegram/etc

image

@peth-yursick   Anything else or is this good to go?

**Review by vidvidvid — APPROVED** [review]
Looks good!

**Comment by HHH-GH** [comment]
cheers vid 👍

**Pull request merged**
