### PR TITLE
D academy updates innkeep

### PR DESCRIPTION
**Pull request by Innkeeping**
## Overview

**What features/fixes does this PR include?**

**Please provide the GitHub issue number**

Closes #

## Follow up Improvement Ideas

- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Comment by Innkeeping** [comment]
@dysbulic I added your docker backend updates to this PR and the test checks are still failing.  Not happy with the arg and env instructions.

**Comment by dysbulic** [comment]
> @dysbulic I added your docker backend updates to this PR and the test checks are still failing. Not happy with the arg and env instructions.

@Innkeeping, that's because you needed to change `packages/backend/codegen.ts` *(like I said)*. 😸

**Comment by Innkeeping** [comment]
My goldfish told me to.

**Review by dysbulic — APPROVED** [review]
Coolio.

**Pull request merged**
