### PR TITLE
Handle Redirection on client side

### LINKED ISSUE #988: Dashboard should only be visible when authenticated
### What would you like to be added?

When a user accesses `/dashboard` and is not logged in, they should be forwarded to `/players`.

### Why is this needed?

The dashboard is full of personalized content, so if there is no one to personalize to the page doesn't make sense.

### PR DESCRIPTION
**Pull request by firattale**
## Overview
The dashboard page should be restricted for unauthorized users.
**What features/fixes does this PR include?**

**Please provide the GitHub issue number**

Closes #988 

## Follow up Improvement Ideas
Redirection has been made on the client side, it would be better if we can do in on server side, but I can't find a way to check if user is authenticated on the server side, any ideas?
- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

### CODE REVIEW

**Review by luxumbra — COMMENTED** [review]
Works for me on the preview. 👍🏻  Agreed with the server side over client side but I am not sure how / if it can be done. @mquellhorst or @alalonde, any thoughts sers?

**Comment by dan13ram** [comment]
I think we should show a loading state and then redirect. Or perhaps just show a huge connect button to login.  
Currently the whole dashboard is displayed for a split second before redirection.

**Comment by luxumbra** [comment]
> I think we should show a loading state and then redirect. Or perhaps just show a huge connect button to login.
> Currently the whole dashboard is displayed for a split second before redirection.

Good point. A large login / connect button and maybe some text "Connect to view your dashboard or create your profile" would be an improvement over a brief flash of the dash.

**Comment by firattale** [comment]
There was a debate here  https://github.com/MetaFam/TheGame/issues/988 about this issue, it is better to close this PR and start with the new plan @luxumbra @dan13ram

**Pull request closed without merging**
