### PR TITLE
fixed 404 on guild detail page request

### PR DESCRIPTION
**Pull request by mquellhorst**

### CODE REVIEW

**Comment by dan13ram** [comment]
@mquellhorst I see that this is a very minor change where you've removed a whitespace character. Is this a mistake?

**Comment by mquellhorst** [comment]
@dan13ram It is a very minor change. The pages didn't work cause the folder was called guild and not guilds so thats why the pages ended up in 404. So a minor change but not only a whitespace

**Comment by dan13ram** [comment]
Ah my bad @mquellhorst I missed the renaming. 
But could you please make the change in `packages/web/components/Guild/GuildTile.tsx` instead to change the link to `guild/*` instead of `guilds/*`?
This is in order to keep the route naming convention same across the board.

**Comment by dan13ram** [comment]
Also please rebase with master

**Comment by mquellhorst** [comment]
I'm on it

**Review by dan13ram — APPROVED** [review]
Great work!

**Pull request merged**
