### PR TITLE
chore: fix ui bug in header

### PR DESCRIPTION
**Pull request by Udit-takkar**
## Overview

Tablet view

Before:-

Screenshot 2023-12-28 at 2 08 23 AM

After:-
Screenshot 2023-12-28 at 2 02 23 AM

Closes #

**Side effects**

### CODE REVIEW

**Review by Seroxdesign — CHANGES_REQUESTED** [review]
image
 still some inconsistencies

**Comment by Udit-takkar** [comment]
@Seroxdesign do you mean the logo not loaded? can you see what the error is while loading

**Comment by Seroxdesign** [comment]
> @Seroxdesign do you mean the logo not loaded? can you see what the error is while loading

Why is the logo next to the searchbar on tablet view instead of all the way at the right/left

**Review by Seroxdesign — APPROVED** [review]
LGTM

**Pull request merged**
