### PR TITLE
1422 Improving UX for Quests

### LINKED ISSUE #1422: [Quests] Improving Quests
On the quests list view:
- [x] Make whole cards clickable, like on /players & /patrons
- [x] Fix bottom row card height (currently appears higher for some reason)
- [x] "Skills" & "Roles" should be at the bottom of the card, regardless of the size of the description. Either that or the description should be a fixed number of rows but @luxumbra mentioned a problem with that I can't recall.
- [x] Change the default number of quests loaded to 50
- [x] Move "read more"
- What it will look like:
image

Inside the quests:
- [x] Fix the card cutoff
- [ ] Add an option to delete quests
- [ ] Increase the size of the "description" box when submitting a quest completion. Right now its a single row.
- [x] There's a weird bug of the creator card getting cut off when under the effect
- [x] Also the creator card looks much narrower than on /players or /patrons - should be the same cards
- [ ] Change the placement of the "claim" button
- [ ] Change the placement of "edit" & "open link" buttons
- [x] Get rid of one of the titles (currently quest title is displayed twice)
- [x] Design & implement the "back to quests" button
- [x] Change the "created by" card to reuse the same component from /players (currently seems hardcoded & different aspect ratio, taller & narrower than on /players, /patrons or /guilds)
- [ ] The "You Gain" aka Reward section should maybe be separated from the description & based on guilds (eg. if the quest is for MetaFam, then it should be that. Currently needs to be copy/pasted to the bottom of every quest & also takes a fair chunk of the description)
- [ ] Have a designer look at the overall design & see what else should be improved
   - [ ] eg. having a side box or something that displays "you gain"

Outside:
- [ ] Making URLs actual names of the quests rather than hashes
- [x] Make sharing URL surface the quest image rather than MG logo

### PR DESCRIPTION
**Pull request by HHH-GH**
This ~~is~~ was a draft PR so that @peth-yursick and @davort can get a look at the changes. Now ready for review

~~I rebased it before opening for review, so there are a bunch of unrelated changed files sorry sorry sorry.~~

Now un-rebased.

## Overview

**What features/fixes does this PR include?**
It's mainly cosmetic changes to match @davort 's upgraded design.
- Covers features/fixes in [Issue 1422](https://github.com/MetaFam/TheGame/issues/1422)
- Upgraded [Quest UI design](https://www.figma.com/file/2yEeQUrgPOrLOq6DpC6Mb7/Quests-UI?node-id=519-2199&t=f7ABDY7Dw2Yxtrsc-0)
- Fixing some links on the Guild join page

**Please provide the GitHub issue number**
Closes #1422

## Key things to review

The changes are mainly Chakra-UI and CSS wrangling, and the actual appearance of it has been ok'd by @peth-yursick and @davort 

So it's just the code implementation to review.

Of particular interest to reviewers (maybe?)

### Link Overlay for QuestTile
Like all the tiles, a block link / LinkBox / LinkOverlay is used to make the whole tile a link target.  

BUT  

I was getting hydration errors while developing because.
- A link wraps the content of the tile
- The Quest description can contain links
- Links inside links cause hydration errors

To fix the hydration errors I made two link boxes. One for the tile header and image, one for the tile body.

Side-effect: the edges of the tile are not included in the block link any more

Question: what's better - ignore hydration errors during development and link the whole tile, or have two link boxes as I've done here?

### 'Link' field is not included in the new design
We couldn't figure out what this was for so we dropped it. 

### Deformatting of description in quest tile

What
- the first part of the full Quest description is used for a shorter description on the Quest Tile
- it's clamped to 3 lines on the quest tile
- If the first line of the Quest description was formatted as a heading, a full-size heading would be displayed in the Quest Tile, which wrecks the design

So
- CSS rules are applied to deformat that description

Question: is my implementation of this acceptable and likely to cover edge cases etc, etc. (Yes, I think?)

Here are some screenshots that illustrate the deformatting

**Before**
image

**After**
image

### Quest image upload
- Currently not working on this deployment due to a missing`$WEB3_STORAGE_TOKEN` in an `.env`
- It works locally, and I didn't change any of that code so all good?

---

This PR is for part 1 of the work. There's more to come in part 2, but the idea is to get the cosmetic changes done and merged first.

---

Click on old notes for more discussion

<details><summary>Old notes</summary>

## Overview

**What features/fixes does this PR include?**
- Covers features/fixes in [Issue 1422](https://github.com/MetaFam/TheGame/issues/1422)
- Updates the design to look like [Quest UI design](https://www.figma.com/file/2yEeQUrgPOrLOq6DpC6Mb7/Quests-UI?node-id=519-2199&t=f7ABDY7Dw2Yxtrsc-0)

**Please provide the GitHub issue number**
Closes #1422

## Notes on what I’ve done so far
- [Quest Explorer page](https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests) matches the new design, and should default to showing 50 quests (if there are actually 50 quests to show) 
- [Quest Details page](https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quest/87b32a6a-3bc3-4df9-91ae-de88ba89460a) matches the new design  

## Questions

Some discussion is required before this PR can come out of draft status.

### Main topics
**At the top of the Quest Explorer page**
- The spacing of the title and the NEW QUEST button gets cramped on the mobile view
- The tooltip (?) doesn't work with touch, hide it for mobile?

image

**In the description part of the quest tile**
- HTML is displayed in here, and if there are paragraphs it makes the text part too tall. A heading in here would probably look crazy. *I would suggest not allowing/displaying HTML in the Quest Tile description.*

image

**Quest Image**
- Would it be better to keep a 4:3-ish ratio as it comes out of the 1:1 ratio for mobile? That would mean we could use one image, and it would look roughly similar in the tile in the Quest Explorer list and on the Quest Details page. (Right now the image gets cropped quite severely on the Quest Details page when shown on a large screen)

image

**Not yet included in the design**
- The tags for 'repetition' and 'unique' and 'open'

image

- The Open Link button (not totally sure what this is for)

image

- The various other buttons (Edit Quest, Delete Quest)
- The Proposals/Quest Completions section. (could probably just change the font of the heading)

image

### Minor topics
- The Quest Filter search option box looks like it was supposed to stick to the top when the page is scrolled (like the Player Filter) but it doesn't—should I make a separate issue about that?
- The Light Italic style for the text in the REWARDS box doesn't appear as light. Options: load another font? Just make it Light, not Light Italic?

image

</summary>

### CODE REVIEW

**Comment by peth-yursick** [comment]
> **At the top of the Quest Explorer page**
> 
>     * The spacing of the title and the NEW QUEST button gets cramped on the mobile view

Yeah, looks like there was no mobile version for this part of the design..

>     * The tooltip (?) doesn't work with touch, hide it for mobile?

This is not the same tooltip as the explanation for rewards, right?

> The tags for 'repetition' and 'unique' and 'open'

I think this was intentional but not sure @davort?

> "HTML is displayed in here, and if there are paragraphs it makes the text part too tall. A heading in here would probably look crazy. I would suggest not allowing/displaying HTML in the Quest Tile description."

Agree. Looks disproportionate & ugly imo, could be fixed by limiting the description to 3 lines of text & having less spacing between the lines of text?

> Would it be better to keep a 4:3-ish ratio as it comes out of the 1:1 ratio for mobile? That would mean we could use one image, and it would look roughly similar in the tile in the Quest Explorer list and on the Quest Details page. (Right now the image gets cropped quite severely on the Quest Details page when shown on a large screen)

Yeah... Almost no image can look good on both 1:1 & 2:1 but not sure how 4:3 fits the description? I guess it could be made taller so it doesn't become narrower than the text box, which wouldn't look good? @davort?

> The Open Link button (not totally sure what this is for)

I guess for when there's more info or something needs to be linked but can't imagine what it could be to require its own button.. Generally anything necessary for the quest can be hyperlinked inside the quest description itself 🤷‍♂️

> The various other buttons (Edit Quest, Delete Quest)

Yeah, @davort said it could be placed better than in the original design but not sure if it made it into the design..
Delete quest didn't exist at all but definitely required.

> The Proposals/Quest Completions section. (could probably just change the font of the heading)

Yeah, changing the font would be good. The "claim quest" should also be retitled to "submit" or something.

Two more things:
- The whole "Note:..." in the rewards blocks was gonna be under a tooltip in the previous version of the design, has this changed?
- In the explorer, when the image bleeds, there's white margins. Would be better if it was at least black but the best way to fix would probably be to have the image zoom in so those margins dont appear at all..

**Comment by davort** [comment]
Hey @HHH-GH - great job with the first build! Now we have a solid platform to refine and fill any gaps we identify. You have already found some and @peth-yursick has weighed in. Time to offer my "2 cents" and keep this rolling forward! :)

===

> At the top of the Quest Explorer page
> 
> The spacing of the title and the NEW QUEST button gets cramped on the mobile view
> The tooltip (?) doesn't work with touch, hide it for mobile?

As peth already said, I didn't cover responsiveness with this view, and it should be done. Let me come back with a similar responsive progression – or regression in this case – as I did for the Quest details page. Generally speaking, I am more in favor of revealing than hiding stuff for mobile, but let's see what it ends up looking like.

===

>> The tags for 'repetition' and 'unique' and 'open'

> I think this was intentional but not sure @davort?

This is my bad. The "quest type" – recurring, unique, personal – provides useful information. Perhaps this info could also be displayed in a more accessible way, since tags don't necessarily give strong enough cue there is more info to be seen when they are hovered by a cursor. And again, on-hover is lost on touchscreens, so all the more reason to avoid that interaction.
as for the "open" or "closed", they are self-explanatory, but still, perhaps we can simplify that further. Leave it to me! :)

===

> "HTML is displayed in here, and if there are paragraphs it makes the text part too tall. A heading in here would probably look crazy. I would suggest not allowing/displaying HTML in the Quest Tile description."

>> Agree. Looks disproportionate & ugly imo, could be fixed by limiting the description to 3 lines of text & having less spacing between the lines of text?

Agreed, let's simplify as peth suggested in his reply.

===

> Would it be better to keep a 4:3-ish ratio as it comes out of the 1:1 ratio for mobile? That would mean we could use one image, and it would look roughly similar in the tile in the Quest Explorer list and on the Quest Details page. (Right now the image gets cropped quite severely on the Quest Details page when shown on a large screen)

>> Yeah... Almost no image can look good on both 1:1 & 2:1 but not sure how 4:3 fits the description? I guess it could be made taller so it doesn't become narrower than the text box, which wouldn't look good? @davort?

FWIW, I'd suggest we instead stick with 4:3 everywhere. There is no ideal solution here, other then asking quest creators to upload two separate images – e.g. 1:1 and 4:3. This would also allow them to customize the "thumbnail" (1:1) and have a full-size 4:3 for quest details.

What do you think?

===

> The various other buttons (Edit Quest, Delete Quest)

>> Yeah, @davort said it could be placed better than in the original design but not sure if it made it into the design..
Delete quest didn't exist at all but definitely required.

Yes, I forgot to find a better solution for this. WIll add it to my list and come back with a proposal.

===

> The whole "Note:..." in the rewards blocks was gonna be under a tooltip in the previous version of the design, has this changed?

Tooltips are black holes for useful info :) Either users won't notice or hover over them, or they just can't do anything with them on mobile. If there are strong reasons for keeping this info hidden/collapsed by default, we can fix that. Let us know @peth-yursick

**Comment by HHH-GH** [comment]
Seems the majority of the notes I made will be covered in the next iteration of the design. Cheers Dave 👍

What's left is:  

**1. Quest image: 1/1, 4/3, other options**
- Can we try keeping the 1/1 image in the list, and the 4/3 on the quest details page? I'll make a demo that will set the quest image to cover the all the space available for it in the design. If the demo looks okay we could keep it like that.
- `In the explorer, when the image bleeds, there's white margins`: I want to quiz the original builders of the image upload part on this. Seems to me that the white margins are added as padding to the actual image, because the image I uploaded was too small. But I wasn't able to find out where in the code that was happening.

**2. Quest description in the list**
- In all the other lists it's set to show 4 lines. What I would like to do is remove all the formatting so there are not gaps between paragraphs and so that the fonts are all the same size. Then the 4 lines will always be the same height. Okay with this? (It's probably easier if I code it up, and then you can see it)

**3. The Open Link button**
- Keep it or not?

Regarding the tool-tips, I agree with Dave on showing that info on the page instead of having the user need to click something to see what happens. Could be replaced with some micro copy, or deleted if not super relevant.

So, next steps for me:
1. Demo of using the same image 1/1 and 4/3
2. Ask builders about the image upload code to see if padding is being added to the image
3. Demo of the de-formatted quest description in the Quest Explorer view

Anything else?

**Comment by HHH-GH** [comment]
>     * `In the explorer, when the image bleeds, there's white margins`: I want to quiz the original builders of the image upload part on this. Seems to me that the white margins are added as padding to the actual image, because the image I uploaded was too small. But I wasn't able to find out where in the code that was happening.

Oops, this is actually me uploading the wrong image.

**Comment by HHH-GH** [comment]
>1. Demo of using the same image 1/1 and 4/3
>3. Demo of the de-formatted quest description in the Quest Explorer view
 
Previews of the above are at https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests

Some screenshots of de-formatted quest descriptions

**Before**

HTML in descriptions before 2

**After**  

HTML in descriptions after 2

(Can you see the little white dot below the heading of the left-most 'after' tile? That's the third row of text not getting masked properly, will fix that with line-height)

**Comment by peth-yursick** [comment]
> Some screenshots of de-formatted quest descriptions

Ahh, much better!
Would still get rid of the fourth line to make them look not so disproportionately tall

**Comment by peth-yursick** [comment]
> * `In the explorer, when the image bleeds, there's white margins`: I want to quiz the original builders of the image upload part on this. Seems to me that the white margins are added as padding to the actual image, because the image I uploaded was too small. But I wasn't able to find out where in the code that was happening.

That was done by @thebeyondr if I'm not mistaken

> Keep it or not?

Feel free to remove

> Regarding the tool-tips, I agree with Dave on showing that info on the page instead of having the user need to click something to see what happens. Could be replaced with some micro copy, or deleted if not super relevant.

Tooltips usually appear on hover, would say whoever is wondering why its "?" would find out, but I may be wrong 🤷‍♂️
Shortened it by a lot, so it should at least fit in a single line now "Note: Rewards vary based on quality of outcome"

**Comment by HHH-GH** [comment]
In the new deployment you'll see:  

**Quest explore page**  
- Quest description clamped to 3 lines maximum
- Proper clipping of long headings

**Quest details page**
- This text added: "Note: Rewards vary based on quality of outcome" in the Quest Descriptions rewards box
- The Quest Status and Repetition tags added below the title and Quest author, basically the same as they are in the current design but a bit bigger
- The Proposals heading at the bottom has a font size/family that matches everything else

On the Quest details page there should still be room for the Edit/Delete button somewhere in the design.

**Comment by HHH-GH** [comment]
Here's where we're up to on this:

**Any suggestions based on the look of what we've done so far?**
* 1/1 and 4/3 images
* How do the tiles on the Quest Explorer page look?
* Does the Quest Details page look okay?

**Next**
* On the Quest Explorer page, the fit of the page heading and New Quest button in mobile view is a bit squeezed
* .. and the tooltip attached to that heading
* On the Quest Details page, the general design of the tags and edit/delete button
* ... and a flow/design for the Delete Quest process
* On the Edit Quest screen, a rework of the form
* ... and I'd try to include preview images for both 1/1 and 4/3 sizes

**Later**
* Various questions for the experts about the implementation of delete quest functionality

**Latest versions**
Quest Explorer https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests
Sample Quest https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quest/9fce19bb-480a-4330-a7fa-fe960e1d141a

**Comment by davort** [comment]
Hey, @HHH-GH - fantastic job! 👏 

> * 1/1 and 4/3 images
> * How do the tiles on the Quest Explorer page look?
> * Does the Quest Details page look okay?

* Love the images! Am I presuming correctly that both 1/1 and 4/3 images are crops of whatever image the quest creator uploads when creating the quest?
* The tiles look very nice! 
* The Quest Details page also looks good. There might be some design decisions – namely the size of the quest title – that might need a 2nd look, but otherwise, it looks ripe for launch to me. Just one small thing - am I, or anyone apart from the quest creator, supposed to see these buttons? 
CleanShot 2023-05-24 at 20 04 25

**Comment by HHH-GH** [comment]
Thanks, Dave. 

> Am I presuming correctly that both 1/1 and 4/3 images are crops of whatever image the quest creator uploads when creating the quest?

I'm using `object-fit: cover` on the image to fit it in the space. There are [examples of it here](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) that show it better than I can tell it. 

The brief version is that one image is uploaded, and CSS object-fit is used to crop it for the display at either aspect ratio. (instead of making two versions of the image when it is uploaded)

> am I, or anyone apart from the quest creator, supposed to see these buttons?

Eventually only the quest creator will see those buttons, but I've got them out and visible so you can see them without having to create your own quest. I'm planning to get your design for them right first, and then I'll put back the code that shows them to the quest creator only.

**Comment by davort** [comment]
> **Next**
> 
> * On the Quest Explorer page, the fit of the page heading and New Quest button in mobile view is a bit squeezed
> * .. and the tooltip attached to that heading

Here's a proposal for the desktop → mobile layout regression for the Quest Explorer page: https://www.figma.com/file/2yEeQUrgPOrLOq6DpC6Mb7/Quests-UI?type=design&node-id=506-2078&t=OHRJZnzzV9zNrddf-4

---

Re: the tooltip → here's a quick demo:

*Tablet*
CleanShot 2023-05-28 at 08 14 44

*Phone*
CleanShot 2023-05-28 at 08 17 51

@HHH-GH - Eager to hear your thoughts!

**Comment by HHH-GH** [comment]
> @HHH-GH - Eager to hear your thoughts!

Works great for me. Just a couple of questions.

For the New Quest/Create Quest button - is it deliberate that it says New Quest on big screens and then Create Quest on smaller screens? I'm assuming that it is not deliberate, and that it's going to be okay if I pick Create Quest to use for text on that button.

For the InfoAccordion, I'll use the specs provided, and is it okay if I put a ~60char limit on the width of the expanded text *inside* the accordion to keep it easily readable?

**Comment by davort** [comment]
> For the New Quest/Create Quest button - is it deliberate that it says New Quest on big screens and then Create Quest on smaller screens? I'm assuming that it is not deliberate, and that it's going to be okay if I pick Create Quest to use for text on that button.

Great catch, and apologies for not making a note about that in Figma! And great choice - generally speaking, verbs are much better at describing what pressing a button will do. Thanks! 🙏 

> For the InfoAccordion, I'll use the specs provided, and is it okay if I put a ~60char limit on the width of the expanded text _inside_ the accordion to keep it easily readable? 

Yes, that will result in showing around 8-10 words in a row, which is just about a perfect length of a row 👍

**Comment by peth-yursick** [comment]
Idk why but the bottom part still looks disproportionately tall to me.. Maybe its because of the spacing between sections or 2 rows or roles, idk.
image
You can see on player cards they look much nicer when the bottom part is shorter, like on all playing cards in general like Pokemon or Gods Unchained..

Anyway, if Dave is fine with it, I'm fine with it 🤷‍♂️
Fine work overall ser Hhh, def don't wish to hold it open any longer!

**Comment by HHH-GH** [comment]
@peth It goes taller when there are multiple rows of skills/roles tags. We could limit the description to two lines instead of three lines. Otherwise there's not much to be done about it.

**Comment by davort** [comment]
Re: cards height - with this current design and layout, it's just how it is. We might also limit the numbers of skills and roles listed in the card, and leave the description the way it is. It boils down to priorities and tradeoffs we're willing to make, @peth-yursick 
How important is it to list more than 2 skills and 2 roles in a card?

**Comment by davort** [comment]
> On the Quest Details page, the general design of the tags and edit/delete button
... and a flow/design for the Delete Quest process

How about this layout for quest creators?
image

And this confirmation modal when they click "Delete quest"?
image

I'd like to hear your thoughts on the following:
1. Content of the confirmation modal, especially regarding the consequences of deleting a quest – I'm not 100% sure what I wrote there is true, technically speaking - @peth-yursick can you advise, please?
2. Any other thoughts about this design - layout and flow?

@HHH-GH - I'll come up with responsive regression later today, and they will be in this section in Figma: https://www.figma.com/file/2yEeQUrgPOrLOq6DpC6Mb7/Quests-UI?type=design&node-id=703-3787&t=b7NuWlxbwlKjRGYI-4

**Comment by peth-yursick** [comment]
> How important is it to list more than 2 skills and 2 roles in a card?

I'd say not very important..
They should appear fully when hovering over "+X" on the card as well as inside the quest itself.

Maybe its good to have 2 rows of skills visible but in that case I'd just remove roles altogether, they seem a bit unnecessary as they are just more generalized version of skills 🤷‍♂️

**Comment by HHH-GH** [comment]
> Content of the confirmation modal, especially regarding the consequences of deleting a quest – I'm not 100% sure what I wrote there is true, technically speaking - @peth-yursick can you advise, please?

I also had questions about that because I guess I'm going to have to program it. 

Common options are:
- it is 100% deleted
- it is marked as deleted but is still in the database; items marked as deleted are not shown in the frontend

?

**Comment by davort** [comment]
> > How important is it to list more than 2 skills and 2 roles in a card?
> 
> I'd say not very important.. They should appear fully when hovering over "+X" on the card as well as inside the quest itself.
> 
> Maybe its good to have 2 rows of skills visible but in that case I'd just remove roles altogether, they seem a bit unnecessary as they are just more generalized version of skills 🤷‍♂️

@HHH-GH 

1. Based on @peth-yursick's reply above, I suggest we remove the "Roles" section from the card.
2. Just to confirm → when there are more skills than fit the allocated space on the card, there is a "+X" appended. Per peth's comment, hovering the "+X" should invoke a tooltip in which all those skills that didn't fit into the card are listed. Would this functionality be a part of your implementation?

**Comment by davort** [comment]
> > Content of the confirmation modal, especially regarding the consequences of deleting a quest – I'm not 100% sure what I wrote there is true, technically speaking - @peth-yursick can you advise, please?
> 
> I also had questions about that because I guess I'm going to have to program it.
> 
> Common options are:
> 
> * it is 100% deleted
> * it is marked as deleted but is still in the database; items marked as deleted are not shown in the frontend
> 
> ?

@peth-yursick → can you validate the contents of the quest deletion confirmation modal? 
Screenshot of the initial design, with my assumptions about what are the consequences of deleting a quest 👇 
CleanShot 2023-05-30 at 15 11 47

We need to inform the user, but also @HHH-GH would appreciate knowing what's the expectation in terms of how things should work if a quest is deleted.

**Comment by peth-yursick** [comment]
> it is marked as deleted but is still in the database; items marked as deleted are not shown in the frontend

Which reminds me it might actually be in use, in the filtering of Quests.. So probably best to keep it in the database.

> @peth-yursick → can you validate the contents of the quest deletion confirmation modal?

I'd ask Alec if this is the case but it would suck if removing the quest also removes it from "completion history" from any player who already completed it before it got deleted.. That would basically mean we can never delete even one-off quests.

**Comment by HHH-GH** [comment]
> 2\. Just to confirm → when there are more skills than fit the allocated space on the card, there is a "+X" appended. Per peth's comment, hovering the "+X" should invoke a tooltip in which all those skills that didn't fit into the card are listed. Would this functionality be a part of your implementation?

I'll have a look to see how that's coded. 

The number of skills that will fit in the allocated space will depend on how long the title of each skill is. What we can do is show X number of skills, and then have the "+X" hover thing as mentioned. X number of skills and the +X bit might fit on two lines, might also wrap to three lines.

**Comment by HHH-GH** [comment]
New previews here:
- Quest Explorer: https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests
- Test Quest https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quest/e302381b-82f8-48e1-abe6-62df307f6943
---
**What's to see?**  
---
**Quest Explorer page**
- limited to 6 skills tags, no roles tags
---
**Quest view page** 
- preview of edit/delete buttons (they don't do anything right now, will add back that functionality later)
- all skills and roles are printed (previously limited to 4)
---
**Also some fixes by request of peth and Musashi13**
- On https://metagame.wtf/join/guild the LFG link is changed to https://metagame.wtf/play/paths/engaged-octos-path
- On https://metagame.wtf/join/guild the NFT links for Rare and Epic go to the correct pages
---
**Next**
- any last changes?
- rebase it and get the code reviewed by the experts
- Part 1 is finished
- Start on Part 2

**Comment by davort** [comment]
> New previews here:
> 
> * Quest Explorer: https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests
> * Test Quest https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quest/e302381b-82f8-48e1-abe6-62df307f6943
> 
> ## **What's to see?**
> **Quest Explorer page**
> 
> * limited to 6 skills tags, no roles tags
> 
> **Quest view page**
> 
> * preview of edit/delete buttons (they don't do anything right now, will add back that functionality later)
> * all skills and roles are printed (previously limited to 4)
> 
> **Also some fixes by request of peth and Musashi13**
> 
> * On https://metagame.wtf/join/guild the LFG link is changed to https://metagame.wtf/play/paths/engaged-octos-path
> * On https://metagame.wtf/join/guild the NFT links for Rare and Epic go to the correct pages
> 
> **Next**
> 
> * any last changes?
> * rebase it and get the code reviewed by the experts
> * Part 1 is finished
> * Start on Part 2

Great work, as always 🙌

One little thing - for the list of Skills in the Quest Explorer page, when there are more than 6 skills listed, there is the "+4 more" (in this particular example). We talked about the remaining 4 skills showing up in a tooltip when this "+4 more" chip is hovered, if I remember correctly. Can't see that in the previews. Did we give up on it because it wasn't feasible?
CleanShot 2023-06-14 at 10 08 55

**Comment by HHH-GH** [comment]
> One little thing - for the list of Skills in the Quest Explorer page, when there are more than 6 skills listed, there is the "+4 more" (in this particular example). We talked about the remaining 4 skills showing up in a tooltip when this "+4 more" chip is hovered, if I remember correctly. Can't see that in the previews. Did we give up on it because it wasn't feasible? CleanShot 2023-06-14 at 10 08 55

I couldn't get that working. But I see it's working on the current version of the quests page so I'll have a look to see what I've done differently.

Is there anything else, aside from that?

**Comment by davort** [comment]
> I couldn't get that working. But I see it's working on the current version of the quests page so I'll have a look to see what I've done differently.
> 
> Is there anything else, aside from that?

Not from my side, that was it.

**Comment by HHH-GH** [comment]
> > I couldn't get that working. But I see it's working on the current version of the quests page so I'll have a look to see what I've done differently.
> > Is there anything else, aside from that?
> 
> Not from my side, that was it.

Thanks for the push, figured it out.

**Quest explorer:** https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quests
**Quest page:** https://frontend-pr-1549-mjhnbmqqna-uk.a.run.app/quest/89fd1511-d773-4e73-b08f-8e863d03ee8d

If @peth-yursick has no further requests then I'll finish off Part 1

To finish
- Edit button only shown if it's your own quest
- Delete button removed (will put back in part 2)
- Rebase and fix any clashes
- Ask the experts for a code review

**Comment by alalonde** [comment]
Can we fix this PR (or open a new one) so that only the actual modification commits are included? 

Reviewing it as-is is much more difficult than it needs to be

**Comment by HHH-GH** [comment]
I've reset it to the commit before the rebase and force-pushed

**Pull request merged**
